sudo: false
language: ruby
rvm:
  - 2.2.1
before_install: gem install bundler -v 1.13.5
addons:
  code_climate:
    repo_token: efd53f9c147e8c05835b200736429a2df29206fa433a7c5e19ceddfe26714d80
after_success:
  - bundle exec codeclimate-test-reporter
