sudo: false
language: ruby
rvm:
  - 2.2.1
before_install: gem install bundler -v 1.13.5
addons:
  code_climate:
    repo_token: 80ee46cf669a13fffbf79e1527f89d5556154fc14dfacb8aab203a910f0ea4d3
after_success:
  - bundle exec codeclimate-test-reporter
